# Generated by Django 3.2.11 on 2022-01-24 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_final', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)], verbose_name='Score Finale')),
                ('is_finished', models.BooleanField(default=False)),
                ('gamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Spare', 'Spare'), ('Strike', 'Strike'), ('Simple', 'Simple')], max_length=250)),
                ('frame_number', models.PositiveIntegerField(verbose_name='Frame Numéro')),
                ('is_done', models.BooleanField(default=False)),
                ('bowling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowlings.bowling')),
            ],
        ),
        migrations.CreateModel(
            name='Lancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancer_number', models.PositiveIntegerField(verbose_name='Lancer Numéro')),
                ('lancer_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)], verbose_name='Nombre de quilles touchées')),
                ('is_additional', models.BooleanField(default=False)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowlings.frame')),
            ],
        ),
    ]
